services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - conversionops_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reco-net

  model-api:
    build:
      context: ./model-api
    environment:
      MODEL_VERSION: v2026.01
    networks:
      - reco-net

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      MODEL_BASE_URL: http://model-api:8000
      CANDIDATE_SOURCE: db
      FEEDBACK_SINK: db
      SPRING_SQL_INIT_MODE: always
      SERVER_PORT: 8080
      API_RATE_LIMIT_STORE: redis
      SPRING_DATA_REDIS_HOST: redis
      API_AUTH_ENABLED: "true"
      API_AUTH_KEY: ${API_AUTH_KEY}
      API_AUTH_ADMIN_KEY: ${API_AUTH_ADMIN_KEY}
    depends_on:
      - postgres
      - model-api
      - redis
    networks:
      - reco-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - reco-net

  gateway:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACTUATOR_BASIC_AUTH_USER: ${ACTUATOR_BASIC_AUTH_USER}
      ACTUATOR_BASIC_AUTH_PASSWORD_HASH: ${ACTUATOR_BASIC_AUTH_PASSWORD_HASH}
    volumes:
      - ./frontend:/srv:ro
      - ./ops/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - model-api
    networks:
      - reco-net

volumes:
  conversionops_pgdata:
  caddy_data:
  caddy_config:

networks:
  reco-net:
